dist: trusty
language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-trusty-6.0
    packages:
      - g++-7
      - clang++-6.0

matrix:
  include:
  - os: linux
    env:
    - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
    - LINKER_FLAGS=""
  - os: linux
    env:
    - MATRIX_EVAL="CC=clang-6.0 && CXX=clang++-6.0"
    - LINKER_FLAGS=""

before_install:
- eval "${MATRIX_EVAL}"

script:
  # CLONE GTEST
  - git clone https://github.com/google/googletest.git
  # BUILD CPP-TUTOR
  - mkdir build
  - cd build
  - cmake  -DCMAKE_BUILD_TYPE=Debug ../
  - make -j8
  # RUN UNIT TESTS
  - ./cppTutorUT
